### ISSUE TITLE
Person nodes can be created with duplicate email addresses

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-api#12]
Email addresses need to be unique across Person nodes. Currently, it is possible to create Person nodes with duplicate email addresses through the api. This can happen through the create or update modes. 

We need to prevent this by checking for existing Person nodes with the passed email address before proceeding with the create or update operation.

**Comment by NoisyFlowers** [comment]
This is in 8ebcd28e48bc507e799ab06ecdac837444da4620. That commit is on the about-those-groups branch and will get folded in when that branch is merged.

**Comment by aazaff** [comment]
Although see https://github.com/paleobot/pbot-dev/issues/43 for other user-related checks to be implemented in the future.
