### ISSUE TITLE
Are we going to provide a graphql UI to our users?

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-api#26]
In addition to our client interface, do we plan to provide a graphql UI to our users (like Apollo Server's Playground)?

I'm not suggesting we build our own; we would make use of an existing tool like Playground. Such tools require introspection on the server. The folks at Apollo apparently think introspection is a [bad idea](https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/) in production. I'm not sure I agree.

**Comment by aazaff** [comment]
Yes.
