### ISSUE TITLE
Remove Specimen connection from Description create and edit

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-api#3]
Right now, when creating a Description, you can link a Specimen in a DECRIBED_BY relationship. When editing a Description, you can change the Specimen.

Because this functionality is also available in Specimen create and edit, I think it should probably be removed from Description. This would simplify logic in Description handling and would be consistent with how we handle other dependent node types.

This would involve changes here and in the client.

**Comment by aazaff** [comment]
It doesn't seem to make sense to us now.
