### ISSUE TITLE
Error querying Specimens when there is a public Specimen COLLECTED_IN only a private collection

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-api#39]
A Specimen must be in a Collection. If it is not, a graphql query on Specimens that includes the Collection fails due to null in non-nullable field.

One way this can happen is if a Specimen is not in a Collection. This shouldn't be possible.

Another way this can happen is if a Specimen is public but it is not collected in a public Collection. This is possible right now.

We need to discuss how groups should work (cascade) with Specimens/Collections.

**Comment by aazaff** [comment]
We know for sure:
1. A public specimen MUST belong to at least 1 public collection.

What we do not know for sure is does it make sense for a specimen to be able to belong to more than 1 collection. I would argue if we are thinking of collection in the PBDB sense of it being like a sampling location - it absolutely does not make sense for a specimen to belong in more than one collection.

**Comment by aazaff** [comment]
New rule:
A specimen can only belong to 1 collection and it will inherit the private/public status of the collection.

**Comment by aazaff** [comment]
User should not be allowed to specify group/private/public when creating specimens, should just auto-inherit from collection as stated above.

**Comment by NoisyFlowers** [comment]
This is in 6382ee95475c9f4dbeec25eb7eb27b53a8792f25 and paleobot/pbot-client@814fe0e3965a441611fe9e9d07cc5ef3c321e48f.

Tangential to this, I also made cascade delete an option on Collection (i.e. when a Collection is delete, can optional delete all its Specimens). This is in 3d89e3f6ff629a93621077262f303975faf22f8b, a0e42f5e3222c43da72654ccb285274bc6b6400a, and paleobot/pbot-client@efb93794e978d674e2fe015b2de28f9fa137cdeb.

**Comment by NoisyFlowers** [comment]
Can we close this one?

**Comment by aazaff** [comment]
Yes, this also seems to be crazy old as far as our issues go? Wonder why it was hanging...
