### ISSUE TITLE
Consider rewriting update resolvers in javascript

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-api#8]
The resolvers that handle delete mutations are all written in javascript. This javascript generates cypher code and uses the Neo4j javascript driver. The advantages of this approach are:

- ability to refactor common cypher generation code into utility routines
- ability to have transactions that span multiple cypher statements
- more flexibility in error handling

The existing update resolvers are working, but we should consider rewriting them to be similar to the delete resolvers.

**Comment by aazaff** [comment]
I believe we decided to do this across the board.

**Comment by NoisyFlowers** [comment]
This is finished. The only resolvers left in  schema.graphql are create and update for CharacterInstance. There are unique bits there that do not lend themselves to cypher-generation in javascript.
